var name = "Vishal Anand";
var school = "D.P.S Public School";
var grade = "9th";
var roll_no = 34;
var marks_math = 89;
var marks_science = 91;
var marks_english = 83;
console.log("");
console.log("########  ***  ℝ𝕖𝕡𝕠𝕣𝕥 ℂ𝕒𝕣𝕕 𝕠𝕗 𝕥𝕙𝕖 𝕊𝕥𝕦𝕕𝕖𝕟𝕥  ***  ########");
console.log("");
console.log("                  Name   :", name);
console.log("                  Grade  :", grade);
console.log("                  Roll No:", roll_no);
console.log("");
console.log(`########  ***  🄼🄰🅁🄺🅂 🄾🄱🅃🄰🄸🄽🄴🄳  ***  ########`);
console.log("");
console.log("     Math     ","     Science     ", "     English     ");
console.log("     ", marks_math, "     ","       ", marks_science, "     ", "       ", marks_english, "     ");
